language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_script:
  - git config --global user.email "year4000@year4000.net"
  - git config --global user.name "Year4000"
script:
  - ./build.sh
